version: '3.9'
services: 
  dev:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - .:/workarea
      - /workarea/build/

    cap_add:
      - SYS_PTRACE

    security_opt: 
      - seccomp:unconfined 

    hostname: dev
    command: sleep infinity